### ISSUE TITLE
/tmp/socket-server-path

### ISSUE THREAD

**Issue by luccam-scr** [scramjetorg/transform-hub#23] opened 2021-08-04 10:49 UTC
**Describe the bug**
After first start, CSH tries to unlink /tmp/socket-server-path even if such link/file doesn't exist

```
ENOENT: no such file or directory, unlink '/tmp/socket-server-path'
```

**Steps to Reproduce**
1. rm /tmp/socket-server-path
2. `scramjet-csi-dev/packages/host/src/bin$ ts-node start.ts`

***Reproduction repo/branch***
scramjet-csi-dev: release/0.10

**Expected behavior**
Test if /tmp/socket-server-path exists and then try to remove/unlink

**Version (please complete the following information):**
 - csi version: release/0.10
 - node version:
node -v
v15.7.0
yarn -v
1.22.10
 - os: ubuntu 20.04

**Comment by alicja-gruzdz** [comment] 2022-02-15 10:34
The issue is now outdated. We moved from the connection via `socket-server-path` between the Supervisor and the STH to TCP connection between the Runner and the STH (the Supervisor lifecycle was absorved into the CSIController in STH).
Closing this issue after the consultation with @pietrzakacper who implemented these changes.

**Closed by alicja-gruzdz** 2022-02-15 10:34 UTC
